# Generated by Django 3.2.8 on 2024-01-29 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import trivia.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('directory', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspective', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('has_perspective', models.BooleanField(default=False)),
                ('share_count', models.IntegerField(blank=True, default=0, null=True)),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_comment_author', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trivia.comment')),
                ('report', models.ManyToManyField(blank=True, default=None, related_name='trivia_comment_report', to=settings.AUTH_USER_MODEL)),
                ('saved', models.ManyToManyField(blank=True, default=None, related_name='trivia_comment_saved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(blank=True, max_length=100000, null=True, upload_to=trivia.models.trivia_to)),
                ('video', models.FileField(blank=True, max_length=1000000, null=True, upload_to=trivia.models.trivia_to)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, max_length=2000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('trivia_type', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
                ('perspective', models.CharField(blank=True, max_length=300, null=True)),
                ('share_count', models.IntegerField(blank=True, default=0, null=True)),
                ('saved_count', models.IntegerField(blank=True, default=0, null=True)),
                ('report_count', models.IntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('has_perspective', models.BooleanField(default=False)),
                ('votes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_author', to=settings.AUTH_USER_MODEL)),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trivia_directory', to='directory.directory')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trivia_page', to='page.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt', to='trivia.trivia')),
                ('report', models.ManyToManyField(blank=True, default=None, related_name='trivia_report', to=settings.AUTH_USER_MODEL)),
                ('saved', models.ManyToManyField(blank=True, default=None, related_name='trivia_saved', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('voters', models.ManyToManyField(related_name='trivia_voters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('is_trivia', models.BooleanField()),
                ('is_comment', models.BooleanField()),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trivia.comment')),
                ('trivia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trivia.trivia')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_voter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_one', models.TextField(blank=True, null=True)),
                ('answer_two', models.TextField(blank=True, null=True)),
                ('answer_three', models.TextField(blank=True, null=True)),
                ('answer_four', models.TextField(blank=True, null=True)),
                ('answer_five', models.TextField(blank=True, null=True)),
                ('answer_is', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('active_for', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_author', to=settings.AUTH_USER_MODEL)),
                ('trivia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trivia.trivia')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='trivia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trivia.trivia'),
        ),
        migrations.AddField(
            model_name='comment',
            name='voters',
            field=models.ManyToManyField(related_name='trivia_comment_voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
