# Generated by Django 3.2.8 on 2024-01-29 04:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('C', 'comment'), ('RP', 'repost'), ('L', 'like'), ('F', 'follow'), ('UF', 'unfollow'), ('M', 'Message')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_has_seen', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.blog')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
