# Generated by Django 3.2.8 on 2024-01-29 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trivia', '0001_initial'),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='trivia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trivia.trivia'),
        ),
    ]
