# Generated by Django 3.2.8 on 2024-01-15 11:59

import account.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=account.models.upload_to)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=account.models.upload_for)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='/^(\\+\\d{1,3}\\s?)?(\\d{1,4}[-.\\s]?)(\\(\\d{1,}\\)|\\d{1,}[-.\\s]?)?(\\d{1,}[-.\\s]?){1,}\\d{1,}$/;')], verbose_name='phone')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='full name')),
                ('bio', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=32, null=True)),
                ('headline', models.CharField(blank=True, max_length=500, null=True)),
                ('call_code', models.CharField(blank=True, max_length=500, null=True)),
                ('otp', models.IntegerField(blank=True, default=0, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('day', models.CharField(blank=True, max_length=3, null=True)),
                ('month', models.CharField(blank=True, max_length=15, null=True)),
                ('year', models.CharField(blank=True, max_length=7, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.BooleanField(blank=True, default=False, verbose_name='author')),
                ('special_user', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Special User')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('two_step_password', models.BooleanField(default=False, help_text='is active two step password?', verbose_name='two step password')),
                ('slug', models.SlugField(blank=True, max_length=1000, unique=True)),
                ('tos', models.BooleanField(default=False)),
                ('created', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked', models.ManyToManyField(blank=True, related_name='user_blocked', to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(blank=True, related_name='user_friends', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_deleted', models.BooleanField(default=False)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommender', to=settings.AUTH_USER_MODEL, verbose_name='Recommender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Recommender',
                'verbose_name_plural': 'Recommenders',
                'ordering': ['-create', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=20, null=True, verbose_name='Company')),
                ('duration', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('is_deleted', models.BooleanField(default=False)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-create', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=20, null=True, verbose_name='Company')),
                ('duration', models.CharField(blank=True, max_length=300, null=True)),
                ('school', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=10000, null=True)),
                ('location', models.CharField(blank=True, max_length=10000, null=True)),
                ('start_at', models.CharField(blank=True, max_length=300, null=True)),
                ('end_at', models.CharField(blank=True, max_length=300, null=True)),
                ('school_url', models.URLField(blank=True, max_length=10000, null=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('is_deleted', models.BooleanField(default=False)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-create', '-id'],
            },
        ),
    ]
