# Generated by Django 3.2.8 on 2024-01-29 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        ('discussion', '0001_initial'),
        ('events', '0001_initial'),
        ('library', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='books',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='record_books', to='library.book'),
        ),
        migrations.AddField(
            model_name='record',
            name='directories',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='record_directories', to='directory.directory'),
        ),
        migrations.AddField(
            model_name='record',
            name='discussions',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='record_discussions', to='discussion.discussion'),
        ),
        migrations.AddField(
            model_name='record',
            name='events',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='record_events', to='events.event'),
        ),
    ]
