# Generated by Django 3.2.8 on 2024-01-15 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
        ('post', '0001_initial'),
        ('blog', '0002_auto_20240115_1259'),
        ('discussion', '0001_initial'),
        ('directory', '0001_initial'),
        ('trivia', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, max_length=100000, null=True)),
                ('collection_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('day', models.CharField(blank=True, max_length=1000, null=True)),
                ('month', models.CharField(blank=True, max_length=1000, null=True)),
                ('year', models.CharField(blank=True, max_length=1000, null=True)),
                ('share_count', models.IntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=1000, unique=True)),
                ('articles', models.ManyToManyField(blank=True, default=None, related_name='articles', to='blog.Blog')),
                ('books', models.ManyToManyField(blank=True, default=None, related_name='books', to='library.Book')),
                ('competitions', models.ManyToManyField(blank=True, default=None, related_name='competitions', to='events.Event')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_creator', to=settings.AUTH_USER_MODEL)),
                ('directories', models.ManyToManyField(blank=True, default=None, related_name='directories', to='directory.Directory')),
                ('discussions', models.ManyToManyField(blank=True, default=None, related_name='discussions', to='discussion.Discussion')),
                ('events', models.ManyToManyField(blank=True, default=None, related_name='events', to='events.Event')),
                ('posts', models.ManyToManyField(blank=True, default=None, related_name='posts', to='post.Post')),
                ('trivias', models.ManyToManyField(blank=True, default=None, related_name='trivias', to='trivia.Trivia')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
