# Generated by Django 3.2.8 on 2024-01-29 04:58

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('collection', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='posts',
            field=models.ManyToManyField(blank=True, default=None, related_name='posts', to='post.Post'),
        ),
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
