# Generated by Django 4.2.9 on 2024-01-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_initial'),
        ('page', '0001_initial'),
        ('library', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='about',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='books',
            field=models.ManyToManyField(blank=True, default=None, related_name='project_books', to='library.book'),
        ),
        migrations.AddField(
            model_name='project',
            name='code_of_conduct',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_directory', to='directory.directory'),
        ),
        migrations.AddField(
            model_name='project',
            name='pages',
            field=models.ManyToManyField(blank=True, default=None, related_name='project_pages', to='page.page'),
        ),
    ]
