# Generated by Django 3.2.8 on 2024-01-29 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='books',
            field=models.ManyToManyField(blank=True, default=None, related_name='directory_books', to='library.Book'),
        ),
        migrations.AddField(
            model_name='directory',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directory',
            name='moderators',
            field=models.ManyToManyField(blank=True, default=None, related_name='directory_moderators', to=settings.AUTH_USER_MODEL),
        ),
    ]
