# Generated by Django 3.2.8 on 2024-01-29 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
        ('project', '0001_initial'),
        ('directory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='pages',
            field=models.ManyToManyField(blank=True, default=None, related_name='directory_pages', to='page.Page'),
        ),
        migrations.AddField(
            model_name='directory',
            name='projects',
            field=models.ManyToManyField(blank=True, default=None, related_name='directory_projects', to='project.Project'),
        ),
        migrations.AddField(
            model_name='directory',
            name='subscribers',
            field=models.ManyToManyField(blank=True, default=None, related_name='directory_subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
