# Generated by Django 3.2.8 on 2024-01-29 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import newsletters.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, max_length=1000000, null=True, upload_to=newsletters.models.file_to)),
                ('frequency', models.CharField(max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=3, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('day', models.CharField(blank=True, max_length=3, null=True)),
                ('month', models.CharField(blank=True, max_length=15, null=True)),
                ('year', models.CharField(blank=True, max_length=7, null=True)),
                ('time', models.CharField(blank=True, max_length=15, null=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='news_likes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_owner', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='news_subscribers', to=settings.AUTH_USER_MODEL)),
                ('target', models.ManyToManyField(blank=True, related_name='news_target', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('cover', models.ImageField(blank=True, max_length=1000000, null=True, upload_to=newsletters.models.post_to)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('day', models.CharField(blank=True, max_length=3, null=True)),
                ('month', models.CharField(blank=True, max_length=15, null=True)),
                ('year', models.CharField(blank=True, max_length=7, null=True)),
                ('time', models.CharField(blank=True, max_length=15, null=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter', to='newsletters.newsletter')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
